import { WordEntry } from './types';

export const wordPool: WordEntry[] = [
  // ==================== GEOGRAPHIE (60) ====================
  { word: 'BERLIN', clue: 'Hauptstadt von Deutschland', category: 'Geographie' },
  { word: 'PARIS', clue: 'Stadt der Liebe an der Seine', category: 'Geographie' },
  { word: 'TOKIO', clue: 'Hauptstadt von Japan', category: 'Geographie' },
  { word: 'KAIRO', clue: 'Hauptstadt am Nil', category: 'Geographie' },
  { word: 'DONAU', clue: 'Zweitlängster Fluss Europas', category: 'Geographie' },
  { word: 'SAHARA', clue: 'Größte Wüste Afrikas', category: 'Geographie' },
  { word: 'AMAZON', clue: 'Größter Fluss Südamerikas (kurz)', category: 'Geographie' },
  { word: 'ALPEN', clue: 'Höchstes Gebirge Europas', category: 'Geographie' },
  { word: 'MALTA', clue: 'Inselstaat im Mittelmeer', category: 'Geographie' },
  { word: 'NIGER', clue: 'Staat und Fluss in Westafrika', category: 'Geographie' },
  { word: 'TIBET', clue: 'Hochland in Zentralasien', category: 'Geographie' },
  { word: 'ANDEN', clue: 'Längste Gebirgskette der Welt', category: 'Geographie' },
  { word: 'KRETA', clue: 'Größte griechische Insel', category: 'Geographie' },
  { word: 'ISLAND', clue: 'Inselstaat mit Geysiren im Nordatlantik', category: 'Geographie' },
  { word: 'ARKTIS', clue: 'Gebiet um den Nordpol', category: 'Geographie' },
  { word: 'BAIKAL', clue: 'Tiefster See der Welt in Sibirien', category: 'Geographie' },
  { word: 'IRLAND', clue: 'Grüne Insel im Atlantik', category: 'Geographie' },
  { word: 'NAIROBI', clue: 'Hauptstadt von Kenia', category: 'Geographie' },
  { word: 'LISSABON', clue: 'Hauptstadt von Portugal', category: 'Geographie' },
  { word: 'MOSKAU', clue: 'Hauptstadt von Russland', category: 'Geographie' },
  { word: 'ATHEN', clue: 'Hauptstadt von Griechenland', category: 'Geographie' },
  { word: 'OSLO', clue: 'Hauptstadt von Norwegen', category: 'Geographie' },
  { word: 'LIMA', clue: 'Hauptstadt von Peru', category: 'Geographie' },
  { word: 'PRAG', clue: 'Hauptstadt von Tschechien', category: 'Geographie' },
  { word: 'WIEN', clue: 'Hauptstadt von Österreich', category: 'Geographie' },
  { word: 'BERN', clue: 'Bundesstadt der Schweiz', category: 'Geographie' },
  { word: 'URAL', clue: 'Grenzgebirge zwischen Europa und Asien', category: 'Geographie' },
  { word: 'KONGO', clue: 'Zweitlängster Fluss Afrikas', category: 'Geographie' },
  { word: 'SUEZ', clue: 'Berühmter Kanal in Ägypten', category: 'Geographie' },
  { word: 'RHEIN', clue: 'Wichtigster Fluss Westdeutschlands', category: 'Geographie' },
  { word: 'ELBE', clue: 'Fluss durch Hamburg', category: 'Geographie' },
  { word: 'ISAR', clue: 'Fluss durch München', category: 'Geographie' },
  { word: 'MOSEL', clue: 'Weinfluss in Rheinland-Pfalz', category: 'Geographie' },
  { word: 'TUNDRA', clue: 'Vegetationszone im hohen Norden', category: 'Geographie' },
  { word: 'STEPPE', clue: 'Baumlose Graslandschaft', category: 'Geographie' },
  { word: 'FJORD', clue: 'Schmale Meeresbucht in Norwegen', category: 'Geographie' },
  { word: 'TAIGA', clue: 'Borealer Nadelwald in Russland', category: 'Geographie' },
  { word: 'KUBA', clue: 'Karibische Insel mit Havanna', category: 'Geographie' },
  { word: 'NEPAL', clue: 'Land am Fuße des Himalaya', category: 'Geographie' },
  { word: 'CHILE', clue: 'Langes schmales Land in Südamerika', category: 'Geographie' },
  { word: 'KOREA', clue: 'Geteilte Halbinsel in Ostasien', category: 'Geographie' },
  { word: 'ZYPERN', clue: 'Drittgrößte Mittelmeerinsel', category: 'Geographie' },
  { word: 'RUEGEN', clue: 'Größte deutsche Insel', category: 'Geographie' },
  { word: 'HAVEL', clue: 'Nebenfluss der Elbe bei Berlin', category: 'Geographie' },
  { word: 'SPREE', clue: 'Fluss durch Berlin', category: 'Geographie' },
  { word: 'ZUGSPITZE', clue: 'Höchster Berg Deutschlands', category: 'Geographie' },
  { word: 'VESUV', clue: 'Berühmter Vulkan bei Neapel', category: 'Geographie' },
  { word: 'ETNA', clue: 'Größter Vulkan Europas auf Sizilien', category: 'Geographie' },
  { word: 'GANGES', clue: 'Heiliger Fluss in Indien', category: 'Geographie' },
  { word: 'HAVANNA', clue: 'Hauptstadt von Kuba', category: 'Geographie' },
  { word: 'OTTAWA', clue: 'Hauptstadt von Kanada', category: 'Geographie' },
  { word: 'HANOI', clue: 'Hauptstadt von Vietnam', category: 'Geographie' },
  { word: 'SEOUL', clue: 'Hauptstadt von Südkorea', category: 'Geographie' },
  { word: 'LAGOS', clue: 'Größte Stadt Nigerias', category: 'Geographie' },
  { word: 'DAKAR', clue: 'Hauptstadt des Senegal', category: 'Geographie' },
  { word: 'RABAT', clue: 'Hauptstadt von Marokko', category: 'Geographie' },
  { word: 'TUNIS', clue: 'Hauptstadt von Tunesien', category: 'Geographie' },
  { word: 'QUITO', clue: 'Hauptstadt von Ecuador', category: 'Geographie' },
  { word: 'NIGER', clue: 'Fluss in Westafrika', category: 'Geographie' },
  { word: 'BODENSEE', clue: 'Größter See am Alpenrand', category: 'Geographie' },

  // ==================== WISSENSCHAFT (50) ====================
  { word: 'ATOM', clue: 'Kleinste Einheit eines Elements', category: 'Wissenschaft' },
  { word: 'NEUTRON', clue: 'Ungeladenes Teilchen im Atomkern', category: 'Wissenschaft' },
  { word: 'PROTON', clue: 'Positiv geladenes Teilchen im Kern', category: 'Wissenschaft' },
  { word: 'QUARK', clue: 'Elementarteilchen der Physik', category: 'Wissenschaft' },
  { word: 'LASER', clue: 'Gebündelter Lichtstrahl', category: 'Wissenschaft' },
  { word: 'PLASMA', clue: 'Vierter Aggregatzustand', category: 'Wissenschaft' },
  { word: 'HELIUM', clue: 'Zweites Element im Periodensystem', category: 'Wissenschaft' },
  { word: 'NEON', clue: 'Edelgas für leuchtende Reklame', category: 'Wissenschaft' },
  { word: 'TITAN', clue: 'Leichtes, stabiles Metall', category: 'Wissenschaft' },
  { word: 'RADIUM', clue: 'Von Marie Curie entdecktes Element', category: 'Wissenschaft' },
  { word: 'ENZYM', clue: 'Biologischer Katalysator', category: 'Wissenschaft' },
  { word: 'GENOM', clue: 'Gesamtheit der Gene eines Organismus', category: 'Wissenschaft' },
  { word: 'MITOSE', clue: 'Zellteilung mit identischen Tochterzellen', category: 'Wissenschaft' },
  { word: 'MEIOSE', clue: 'Zellteilung zur Bildung von Keimzellen', category: 'Wissenschaft' },
  { word: 'OSMOSE', clue: 'Diffusion durch eine Membran', category: 'Wissenschaft' },
  { word: 'PHOTON', clue: 'Lichtteilchen ohne Masse', category: 'Wissenschaft' },
  { word: 'BOSON', clue: 'Teilchenklasse in der Quantenphysik', category: 'Wissenschaft' },
  { word: 'ISOTOP', clue: 'Atomvariante mit anderer Neutronenzahl', category: 'Wissenschaft' },
  { word: 'MAGNET', clue: 'Objekt das Eisen anzieht', category: 'Wissenschaft' },
  { word: 'VAKUUM', clue: 'Luftleerer Raum', category: 'Wissenschaft' },
  { word: 'FORMEL', clue: 'Mathematischer oder chemischer Ausdruck', category: 'Wissenschaft' },
  { word: 'THESE', clue: 'Wissenschaftliche Behauptung', category: 'Wissenschaft' },
  { word: 'LABOR', clue: 'Ort für wissenschaftliche Experimente', category: 'Wissenschaft' },
  { word: 'FOKUS', clue: 'Brennpunkt einer Linse', category: 'Wissenschaft' },
  { word: 'PRISMA', clue: 'Zerteilt Licht in Regenbogenfarben', category: 'Wissenschaft' },
  { word: 'VOLT', clue: 'Einheit der elektrischen Spannung', category: 'Wissenschaft' },
  { word: 'WATT', clue: 'Einheit der Leistung', category: 'Wissenschaft' },
  { word: 'AMPERE', clue: 'Einheit der Stromstärke', category: 'Wissenschaft' },
  { word: 'NEWTON', clue: 'Einheit der Kraft', category: 'Wissenschaft' },
  { word: 'TESLA', clue: 'Einheit der magnetischen Flussdichte', category: 'Wissenschaft' },
  { word: 'JOULE', clue: 'Einheit der Energie', category: 'Wissenschaft' },
  { word: 'HERTZ', clue: 'Einheit der Frequenz', category: 'Wissenschaft' },
  { word: 'MOLEKUEL', clue: 'Verbindung aus mehreren Atomen', category: 'Wissenschaft' },
  { word: 'ELEKTRON', clue: 'Negativ geladenes Teilchen', category: 'Wissenschaft' },
  { word: 'ZELLE', clue: 'Grundbaustein aller Lebewesen', category: 'Wissenschaft' },
  { word: 'RETORTE', clue: 'Kolbenförmiges Laborgefäß', category: 'Wissenschaft' },
  { word: 'PIPETTE', clue: 'Laborgerät zum Dosieren von Flüssigkeiten', category: 'Wissenschaft' },
  { word: 'ACHSE', clue: 'Drehpunkt oder Symmetrielinie', category: 'Wissenschaft' },
  { word: 'DICHTE', clue: 'Masse pro Volumen', category: 'Wissenschaft' },
  { word: 'MASSE', clue: 'Physikalische Eigenschaft eines Körpers', category: 'Wissenschaft' },
  { word: 'KRAFT', clue: 'Ursache von Beschleunigung (Physik)', category: 'Wissenschaft' },
  { word: 'IMPULS', clue: 'Produkt aus Masse und Geschwindigkeit', category: 'Wissenschaft' },
  { word: 'DRUCK', clue: 'Kraft pro Fläche', category: 'Wissenschaft' },
  { word: 'HEBEL', clue: 'Einfache Maschine zum Kraftverstärken', category: 'Wissenschaft' },
  { word: 'SPULE', clue: 'Gewickelter Draht für Magnetfelder', category: 'Wissenschaft' },
  { word: 'DIODE', clue: 'Elektronisches Bauteil als Einwegventil', category: 'Wissenschaft' },
  { word: 'SENSOR', clue: 'Gerät zur Messwerterfassung', category: 'Wissenschaft' },
  { word: 'REAGENS', clue: 'Stoff zur chemischen Analyse', category: 'Wissenschaft' },
  { word: 'AXIOM', clue: 'Grundsatz der nicht bewiesen werden muss', category: 'Wissenschaft' },
  { word: 'HYPOTHESE', clue: 'Unbewiesene wissenschaftliche Annahme', category: 'Wissenschaft' },

  // ==================== TIERE (50) ====================
  { word: 'ADLER', clue: 'König der Lüfte', category: 'Tiere' },
  { word: 'LACHS', clue: 'Wanderfisch der stromaufwärts schwimmt', category: 'Tiere' },
  { word: 'IGEL', clue: 'Stacheliges Säugetier', category: 'Tiere' },
  { word: 'PANDA', clue: 'Schwarz-weißer Bär aus China', category: 'Tiere' },
  { word: 'KOALA', clue: 'Australisches Beuteltier im Eukalyptus', category: 'Tiere' },
  { word: 'ELCH', clue: 'Größter lebender Hirsch', category: 'Tiere' },
  { word: 'FALKE', clue: 'Schnellster Vogel im Sturzflug', category: 'Tiere' },
  { word: 'GECKO', clue: 'Eidechse die an Wänden klettert', category: 'Tiere' },
  { word: 'NARWAL', clue: 'Wal mit langem Stoßzahn', category: 'Tiere' },
  { word: 'OTTER', clue: 'Verspieltes Wassertier mit Fell', category: 'Tiere' },
  { word: 'STORCH', clue: 'Vogel der angeblich Babys bringt', category: 'Tiere' },
  { word: 'BIBER', clue: 'Nager der Dämme baut', category: 'Tiere' },
  { word: 'MOLCH', clue: 'Amphibie die im Wasser lebt', category: 'Tiere' },
  { word: 'LUCHS', clue: 'Europäische Wildkatze mit Pinselohren', category: 'Tiere' },
  { word: 'MARDER', clue: 'Kleines Raubtier das Autokabel beißt', category: 'Tiere' },
  { word: 'REIHER', clue: 'Langbeiniger Wasservogel', category: 'Tiere' },
  { word: 'DROSSEL', clue: 'Singvogel der melodisch singt', category: 'Tiere' },
  { word: 'KRABBE', clue: 'Meerestier mit Scheren', category: 'Tiere' },
  { word: 'HUMMER', clue: 'Großer Meereskrebs als Delikatesse', category: 'Tiere' },
  { word: 'QUALLE', clue: 'Gallertiges Meerestier', category: 'Tiere' },
  { word: 'KROKODIL', clue: 'Großes Reptil im Wasser', category: 'Tiere' },
  { word: 'DELPHIN', clue: 'Intelligentes Meeressäugetier', category: 'Tiere' },
  { word: 'PAPAGEI', clue: 'Bunter Vogel der sprechen kann', category: 'Tiere' },
  { word: 'FLAMINGO', clue: 'Rosa Vogel der auf einem Bein steht', category: 'Tiere' },
  { word: 'PINGUIN', clue: 'Flugunfähiger Vogel der Antarktis', category: 'Tiere' },
  { word: 'HAMSTER', clue: 'Kleines Nagetier mit Backentaschen', category: 'Tiere' },
  { word: 'DACHS', clue: 'Schwarz-weiß gestreiftes Gesicht, lebt im Bau', category: 'Tiere' },
  { word: 'FASAN', clue: 'Bunter Hühnervogel', category: 'Tiere' },
  { word: 'WIESEL', clue: 'Kleinstes Raubtier Europas', category: 'Tiere' },
  { word: 'BUSSARD', clue: 'Häufigster Greifvogel in Deutschland', category: 'Tiere' },
  { word: 'SPECHT', clue: 'Vogel der an Bäume klopft', category: 'Tiere' },
  { word: 'MURMELTIER', clue: 'Alpenbewohner der Winterschlaf hält', category: 'Tiere' },
  { word: 'CHAMÄLEON', clue: 'Reptil das seine Farbe wechselt', category: 'Tiere' },
  { word: 'KOLIBRI', clue: 'Kleinster Vogel der Welt', category: 'Tiere' },
  { word: 'GAZELLE', clue: 'Schnelle Antilope Afrikas', category: 'Tiere' },
  { word: 'GORILLA', clue: 'Größter lebender Menschenaffe', category: 'Tiere' },
  { word: 'HYAENE', clue: 'Afrikanisches Raubtier mit Lachen', category: 'Tiere' },
  { word: 'GEPARD', clue: 'Schnellstes Landtier der Welt', category: 'Tiere' },
  { word: 'ZEBRA', clue: 'Gestreiftes Pferd aus Afrika', category: 'Tiere' },
  { word: 'GIRAFFE', clue: 'Langhalsiges Tier Afrikas', category: 'Tiere' },
  { word: 'NILPFERD', clue: 'Schweres Tier das im Wasser lebt', category: 'Tiere' },
  { word: 'PANTHER', clue: 'Schwarzer Leopard', category: 'Tiere' },
  { word: 'BISON', clue: 'Großer nordamerikanischer Wildrind', category: 'Tiere' },
  { word: 'WOLF', clue: 'Stammvater des Hundes', category: 'Tiere' },
  { word: 'FUCHS', clue: 'Schlaues rotpelziges Raubtier', category: 'Tiere' },
  { word: 'HASE', clue: 'Langohr auf dem Feld', category: 'Tiere' },
  { word: 'RABE', clue: 'Intelligenter schwarzer Vogel', category: 'Tiere' },
  { word: 'SCHWAN', clue: 'Eleganter weißer Wasservogel', category: 'Tiere' },
  { word: 'EULE', clue: 'Nachtaktiver Greifvogel', category: 'Tiere' },
  { word: 'SEEHUND', clue: 'Robbe an Nord- und Ostsee', category: 'Tiere' },

  // ==================== KULTUR & KUNST (40) ====================
  { word: 'OPER', clue: 'Musikalisches Bühnenwerk', category: 'Kultur' },
  { word: 'ROMAN', clue: 'Längere literarische Erzählung', category: 'Kultur' },
  { word: 'BALLETT', clue: 'Klassischer Bühnentanz', category: 'Kultur' },
  { word: 'FRESKO', clue: 'Wandmalerei auf nassem Putz', category: 'Kultur' },
  { word: 'LYRIK', clue: 'Dichtkunst in Versform', category: 'Kultur' },
  { word: 'EPIK', clue: 'Erzählende Literaturgattung', category: 'Kultur' },
  { word: 'DRAMA', clue: 'Theaterstück als Literaturgattung', category: 'Kultur' },
  { word: 'SKULPTUR', clue: 'Dreidimensionales Kunstwerk', category: 'Kultur' },
  { word: 'GALERIE', clue: 'Ausstellungsraum für Kunst', category: 'Kultur' },
  { word: 'MUSEUM', clue: 'Haus für Sammlungen und Ausstellungen', category: 'Kultur' },
  { word: 'SONATE', clue: 'Mehrsätziges Musikstück', category: 'Kultur' },
  { word: 'HYMNE', clue: 'Feierliches Loblied', category: 'Kultur' },
  { word: 'FABEL', clue: 'Lehrhafte Tiergeschichte', category: 'Kultur' },
  { word: 'MYTHOS', clue: 'Alte Götter- und Heldensage', category: 'Kultur' },
  { word: 'SATIRE', clue: 'Spottende Darstellung von Missständen', category: 'Kultur' },
  { word: 'ELEGIE', clue: 'Klagedicht der Antike', category: 'Kultur' },
  { word: 'MOSAIK', clue: 'Bild aus kleinen Steinchen', category: 'Kultur' },
  { word: 'RELIEF', clue: 'Erhabene Bildhauerarbeit auf einer Fläche', category: 'Kultur' },
  { word: 'PODIUM', clue: 'Erhöhte Plattform für Redner', category: 'Kultur' },
  { word: 'PROLOG', clue: 'Einleitung eines Theaterstücks', category: 'Kultur' },
  { word: 'EPILOG', clue: 'Nachwort oder Schlusswort', category: 'Kultur' },
  { word: 'NOVELLE', clue: 'Kürzere Erzählung mit Wendepunkt', category: 'Kultur' },
  { word: 'GRAFIK', clue: 'Gedrucktes oder gezeichnetes Bild', category: 'Kultur' },
  { word: 'MASKE', clue: 'Gesichtsbedeckung im Theater', category: 'Kultur' },
  { word: 'REGIE', clue: 'Künstlerische Leitung eines Films', category: 'Kultur' },
  { word: 'REQUISIT', clue: 'Gegenstand auf der Theaterbühne', category: 'Kultur' },
  { word: 'ARIE', clue: 'Gesangsstück in einer Oper', category: 'Kultur' },
  { word: 'DUETT', clue: 'Musikstück für zwei Stimmen', category: 'Kultur' },
  { word: 'TRIO', clue: 'Musikgruppe aus drei Personen', category: 'Kultur' },
  { word: 'OUVERTUERE', clue: 'Eröffnungsmusik einer Oper', category: 'Kultur' },
  { word: 'LIBRETTO', clue: 'Textbuch einer Oper', category: 'Kultur' },
  { word: 'SINFONIE', clue: 'Großes Orchesterwerk in Sätzen', category: 'Kultur' },
  { word: 'AQUARELL', clue: 'Malerei mit Wasserfarben', category: 'Kultur' },
  { word: 'PASTELL', clue: 'Zeichnung mit weichen Farbstiften', category: 'Kultur' },
  { word: 'STILLLEBEN', clue: 'Malerei unbelebter Gegenstände', category: 'Kultur' },
  { word: 'PORTRAIT', clue: 'Bildnis eines Menschen', category: 'Kultur' },
  { word: 'BAROCK', clue: 'Kunststil des 17. Jahrhunderts', category: 'Kultur' },
  { word: 'GOTIK', clue: 'Mittelalterlicher Baustil mit Spitzbögen', category: 'Kultur' },
  { word: 'ROKOKO', clue: 'Verspielter Kunststil des 18. Jahrhunderts', category: 'Kultur' },
  { word: 'JUGENDSTIL', clue: 'Kunstrichtung um 1900 mit floralen Formen', category: 'Kultur' },

  // ==================== ESSEN & TRINKEN (35) ====================
  { word: 'BREZEL', clue: 'Typisches Laugengebäck', category: 'Essen' },
  { word: 'RISOTTO', clue: 'Italienisches Reisgericht', category: 'Essen' },
  { word: 'SUSHI', clue: 'Japanische Reishäppchen', category: 'Essen' },
  { word: 'GULASCH', clue: 'Ungarisches Fleischgericht', category: 'Essen' },
  { word: 'TOFU', clue: 'Sojaprodukt als Fleischersatz', category: 'Essen' },
  { word: 'OLIVEN', clue: 'Mediterrane Steinfrüchte', category: 'Essen' },
  { word: 'MANGO', clue: 'Tropische Steinfrucht', category: 'Essen' },
  { word: 'QUICHE', clue: 'Französischer Gemüsekuchen', category: 'Essen' },
  { word: 'FONDUE', clue: 'Schweizer Käsegericht zum Eintauchen', category: 'Essen' },
  { word: 'CROISSANT', clue: 'Französisches Buttergebäck', category: 'Essen' },
  { word: 'ESPRESSO', clue: 'Starker kleiner Kaffee aus Italien', category: 'Essen' },
  { word: 'PRALINE', clue: 'Edle Schokoladenkonfekt', category: 'Essen' },
  { word: 'MARZIPAN', clue: 'Süße Mandelmasse aus Lübeck', category: 'Essen' },
  { word: 'PASTA', clue: 'Italienische Teigwaren', category: 'Essen' },
  { word: 'PESTO', clue: 'Italienische Basilikumsauce', category: 'Essen' },
  { word: 'CURRY', clue: 'Indisches Gewürzgericht', category: 'Essen' },
  { word: 'KEBAB', clue: 'Gegrilltes Fleisch am Spieß', category: 'Essen' },
  { word: 'PAELLA', clue: 'Spanisches Reisgericht mit Meeresfrüchten', category: 'Essen' },
  { word: 'TAPAS', clue: 'Spanische kleine Appetithäppchen', category: 'Essen' },
  { word: 'CREPE', clue: 'Dünner französischer Pfannkuchen', category: 'Essen' },
  { word: 'WAFFEL', clue: 'Gebäck mit Rautenmuster', category: 'Essen' },
  { word: 'KNOBLAUCH', clue: 'Scharfe Gewürzpflanze gegen Vampire', category: 'Essen' },
  { word: 'BASILIKUM', clue: 'Grünes Kraut auf Pizza und Pasta', category: 'Essen' },
  { word: 'SAFRAN', clue: 'Teuerstes Gewürz der Welt', category: 'Essen' },
  { word: 'VANILLE', clue: 'Süßes Gewürz aus Orchideenschoten', category: 'Essen' },
  { word: 'ZIMT', clue: 'Weihnachtliches Rindengewürz', category: 'Essen' },
  { word: 'INGWER', clue: 'Scharfe Wurzelknolle aus Asien', category: 'Essen' },
  { word: 'AVOCADO', clue: 'Grüne Frucht für Guacamole', category: 'Essen' },
  { word: 'ANANAS', clue: 'Tropische Frucht mit Schopf', category: 'Essen' },
  { word: 'TRAUBE', clue: 'Frucht für Wein', category: 'Essen' },
  { word: 'FEIGE', clue: 'Süße mediterrane Frucht', category: 'Essen' },
  { word: 'DATTEL', clue: 'Süße Palmenfrucht aus der Wüste', category: 'Essen' },
  { word: 'GNOCCHI', clue: 'Italienische Kartoffelklößchen', category: 'Essen' },
  { word: 'RAVIOLI', clue: 'Gefüllte italienische Teigtaschen', category: 'Essen' },
  { word: 'TIRAMISU', clue: 'Italienisches Dessert mit Mascarpone', category: 'Essen' },

  // ==================== SPORT (40) ====================
  { word: 'RUGBY', clue: 'Ballsport mit ovalem Ball', category: 'Sport' },
  { word: 'SPRINT', clue: 'Kurzstreckenlauf', category: 'Sport' },
  { word: 'SLALOM', clue: 'Zickzacklauf im Skisport', category: 'Sport' },
  { word: 'DOPING', clue: 'Verbotene Leistungssteigerung im Sport', category: 'Sport' },
  { word: 'FLANKE', clue: 'Hoher Pass von der Seite im Fußball', category: 'Sport' },
  { word: 'VOLLEY', clue: 'Ball direkt aus der Luft spielen', category: 'Sport' },
  { word: 'ABSEITS', clue: 'Regelverstoß im Fußball', category: 'Sport' },
  { word: 'FREISTOSS', clue: 'Ruhender Ball nach einem Foul', category: 'Sport' },
  { word: 'MARATHON', clue: 'Lauf über 42,195 Kilometer', category: 'Sport' },
  { word: 'TRIATHLON', clue: 'Dreikampf: Schwimmen, Rad, Lauf', category: 'Sport' },
  { word: 'BIATHLON', clue: 'Skilanglauf und Schießen', category: 'Sport' },
  { word: 'HOCKEY', clue: 'Mannschaftssport mit Schläger und Puck', category: 'Sport' },
  { word: 'TENNIS', clue: 'Rückschlagspiel über ein Netz', category: 'Sport' },
  { word: 'SQUASH', clue: 'Rückschlagspiel in einem Raum', category: 'Sport' },
  { word: 'JUDO', clue: 'Japanischer Kampfsport mit Würfen', category: 'Sport' },
  { word: 'KARATE', clue: 'Japanischer Kampfsport mit Schlägen', category: 'Sport' },
  { word: 'BOXEN', clue: 'Kampfsport mit Fäusten', category: 'Sport' },
  { word: 'FECHTEN', clue: 'Kampfsport mit Degen oder Florett', category: 'Sport' },
  { word: 'CURLING', clue: 'Eissport mit poliertem Stein', category: 'Sport' },
  { word: 'POLO', clue: 'Reitersport mit Schläger', category: 'Sport' },
  { word: 'GOLF', clue: 'Ballsport mit 18 Löchern', category: 'Sport' },
  { word: 'KRICKET', clue: 'Englischer Schlagballsport', category: 'Sport' },
  { word: 'PARCOURS', clue: 'Hindernisbahn im Reitsport', category: 'Sport' },
  { word: 'STAFFEL', clue: 'Laufwettbewerb mit Stabübergabe', category: 'Sport' },
  { word: 'TORWART', clue: 'Hüter des Tores im Fußball', category: 'Sport' },
  { word: 'ELFMETER', clue: 'Strafstoß aus elf Metern', category: 'Sport' },
  { word: 'PODEST', clue: 'Siegertreppchen bei Wettkämpfen', category: 'Sport' },
  { word: 'REKORD', clue: 'Bestleistung im Sport', category: 'Sport' },
  { word: 'POKAL', clue: 'Siegestrophäe im Sport', category: 'Sport' },
  { word: 'MEDAILLE', clue: 'Gold, Silber oder Bronze', category: 'Sport' },
  { word: 'TRAINER', clue: 'Betreuer einer Mannschaft', category: 'Sport' },
  { word: 'ATHLET', clue: 'Sportler bei Wettkämpfen', category: 'Sport' },
  { word: 'OLYMPIA', clue: 'Größtes Sportereignis der Welt', category: 'Sport' },
  { word: 'DRIBBLING', clue: 'Ballführung im Fußball oder Basketball', category: 'Sport' },
  { word: 'AUFSCHLAG', clue: 'Erster Schlag beim Tennis', category: 'Sport' },
  { word: 'ABFAHRT', clue: 'Schnellste Disziplin im Skirennen', category: 'Sport' },
  { word: 'RUNDE', clue: 'Zeitabschnitt beim Boxen', category: 'Sport' },
  { word: 'HALBZEIT', clue: 'Pause in der Mitte des Spiels', category: 'Sport' },
  { word: 'FINALE', clue: 'Endspiel eines Turniers', category: 'Sport' },
  { word: 'TAKTIK', clue: 'Planmäßiges Vorgehen im Sport', category: 'Sport' },

  // ==================== TECHNIK (40) ====================
  { word: 'PIXEL', clue: 'Kleinster Bildpunkt am Bildschirm', category: 'Technik' },
  { word: 'ROUTER', clue: 'Gerät zur Internetverteilung', category: 'Technik' },
  { word: 'CLOUD', clue: 'Datenspeicher im Internet', category: 'Technik' },
  { word: 'AVATAR', clue: 'Digitale Spielfigur oder Profilbild', category: 'Technik' },
  { word: 'CURSOR', clue: 'Blinkende Eingabemarke am Bildschirm', category: 'Technik' },
  { word: 'BACKUP', clue: 'Sicherungskopie von Daten', category: 'Technik' },
  { word: 'SERVER', clue: 'Computer der Dienste bereitstellt', category: 'Technik' },
  { word: 'DOMAIN', clue: 'Internetadresse einer Webseite', category: 'Technik' },
  { word: 'LAPTOP', clue: 'Tragbarer Computer', category: 'Technik' },
  { word: 'TABLET', clue: 'Tragbarer Flachcomputer mit Touchscreen', category: 'Technik' },
  { word: 'DROHNE', clue: 'Unbemanntes Fluggerät', category: 'Technik' },
  { word: 'ROBOTER', clue: 'Programmierte Maschine', category: 'Technik' },
  { word: 'HYBRID', clue: 'Mischung aus zwei Antriebsarten', category: 'Technik' },
  { word: 'FIREWALL', clue: 'Netzwerk-Schutzprogramm', category: 'Technik' },
  { word: 'FESTPLATTE', clue: 'Dauerhafter Datenspeicher im PC', category: 'Technik' },
  { word: 'PROZESSOR', clue: 'Recheneinheit des Computers', category: 'Technik' },
  { word: 'MONITOR', clue: 'Bildschirm eines Computers', category: 'Technik' },
  { word: 'MODEM', clue: 'Gerät für Internetverbindung', category: 'Technik' },
  { word: 'WIDGET', clue: 'Kleines Programmelement auf dem Bildschirm', category: 'Technik' },
  { word: 'UPDATE', clue: 'Software-Aktualisierung', category: 'Technik' },
  { word: 'BROWSER', clue: 'Programm zum Surfen im Internet', category: 'Technik' },
  { word: 'KAMERA', clue: 'Gerät zum Fotografieren', category: 'Technik' },
  { word: 'ANTENNE', clue: 'Gerät zum Empfangen von Signalen', category: 'Technik' },
  { word: 'PLATINE', clue: 'Träger elektronischer Bauteile', category: 'Technik' },
  { word: 'AKKU', clue: 'Wiederaufladbare Batterie', category: 'Technik' },
  { word: 'CHIP', clue: 'Winziges Halbleiterbauteil', category: 'Technik' },
  { word: 'DISPLAY', clue: 'Anzeigeeinheit eines Geräts', category: 'Technik' },
  { word: 'BLUETOOTH', clue: 'Drahtlose Nahfunktechnik', category: 'Technik' },
  { word: 'STREAMING', clue: 'Datenübertragung in Echtzeit', category: 'Technik' },
  { word: 'PODCAST', clue: 'Digitale Radiosendung zum Abrufen', category: 'Technik' },
  { word: 'HASHTAG', clue: 'Schlagwort mit Rautezeichen', category: 'Technik' },
  { word: 'EMOJI', clue: 'Kleines Bildzeichen in Nachrichten', category: 'Technik' },
  { word: 'SELFIE', clue: 'Selbstportrait mit dem Handy', category: 'Technik' },
  { word: 'SCANNER', clue: 'Gerät zum Digitalisieren von Dokumenten', category: 'Technik' },
  { word: 'TURBINE', clue: 'Maschine angetrieben durch Strömung', category: 'Technik' },
  { word: 'DYNAMO', clue: 'Maschine die Strom durch Drehung erzeugt', category: 'Technik' },
  { word: 'KOLBEN', clue: 'Bewegliches Teil im Motor', category: 'Technik' },
  { word: 'GETRIEBE', clue: 'Mechanik zur Kraftübertragung im Auto', category: 'Technik' },
  { word: 'ENCODER', clue: 'Gerät zur Signalumwandlung', category: 'Technik' },
  { word: 'ALGORITHMUS', clue: 'Rechenvorschrift in der Informatik', category: 'Technik' },

  // ==================== NATUR (40) ====================
  { word: 'BIOTOP', clue: 'Natürlicher Lebensraum von Tieren', category: 'Natur' },
  { word: 'GEYSER', clue: 'Heiße Springquelle', category: 'Natur' },
  { word: 'AURORA', clue: 'Polarlicht am Himmel', category: 'Natur' },
  { word: 'NEBEL', clue: 'Bodennah schwebende Wolke', category: 'Natur' },
  { word: 'LAUB', clue: 'Blätter der Bäume', category: 'Natur' },
  { word: 'MOOR', clue: 'Feuchtes Sumpfgebiet mit Torf', category: 'Natur' },
  { word: 'RIFF', clue: 'Unterwasser-Felsgebilde aus Korallen', category: 'Natur' },
  { word: 'LAVA', clue: 'Geschmolzenes Gestein aus Vulkanen', category: 'Natur' },
  { word: 'BASALT', clue: 'Dunkles vulkanisches Gestein', category: 'Natur' },
  { word: 'GRANIT', clue: 'Hartes Tiefengestein', category: 'Natur' },
  { word: 'QUARZ', clue: 'Häufigstes Mineral der Erdkruste', category: 'Natur' },
  { word: 'BERNSTEIN', clue: 'Fossiles Baumharz', category: 'Natur' },
  { word: 'FLUT', clue: 'Steigendes Wasser an der Küste', category: 'Natur' },
  { word: 'EBBE', clue: 'Sinkendes Wasser der Gezeiten', category: 'Natur' },
  { word: 'TSUNAMI', clue: 'Riesige Flutwelle durch Seebeben', category: 'Natur' },
  { word: 'MONSUN', clue: 'Jahreszeitlicher Regen in Asien', category: 'Natur' },
  { word: 'TORNADO', clue: 'Gewaltiger Wirbelsturm an Land', category: 'Natur' },
  { word: 'ORKAN', clue: 'Sehr starker Sturm', category: 'Natur' },
  { word: 'EROSION', clue: 'Abtragung von Gestein durch Wind und Wasser', category: 'Natur' },
  { word: 'FOSSIL', clue: 'Versteinerter Überrest eines Lebewesens', category: 'Natur' },
  { word: 'GLETSCHER', clue: 'Eismasse die sich langsam bewegt', category: 'Natur' },
  { word: 'KRATER', clue: 'Trichterförmige Vertiefung eines Vulkans', category: 'Natur' },
  { word: 'MAGMA', clue: 'Heißes flüssiges Gestein unter der Erde', category: 'Natur' },
  { word: 'OASE', clue: 'Grüne Stelle in der Wüste', category: 'Natur' },
  { word: 'DUENE', clue: 'Sandberg an der Küste', category: 'Natur' },
  { word: 'EICHE', clue: 'Kräftiger Laubbaum mit Eicheln', category: 'Natur' },
  { word: 'BIRKE', clue: 'Baum mit weißer Rinde', category: 'Natur' },
  { word: 'BUCHE', clue: 'Verbreiteter Laubbaum in Europa', category: 'Natur' },
  { word: 'TANNE', clue: 'Immergrüner Nadelbaum', category: 'Natur' },
  { word: 'KIEFER', clue: 'Nadelbaum mit langen Nadeln', category: 'Natur' },
  { word: 'LINDE', clue: 'Baum mit herzförmigen Blättern', category: 'Natur' },
  { word: 'AHORN', clue: 'Baum mit handförmigen Blättern', category: 'Natur' },
  { word: 'ORCHIDEE', clue: 'Edle tropische Blume', category: 'Natur' },
  { word: 'TULPE', clue: 'Beliebte Frühlingsblume aus Holland', category: 'Natur' },
  { word: 'FARN', clue: 'Uralte Grünpflanze ohne Blüten', category: 'Natur' },
  { word: 'ALGE', clue: 'Einfache Wasserpflanze', category: 'Natur' },
  { word: 'MOOS', clue: 'Weiches grünes Polsterpflänzchen', category: 'Natur' },
  { word: 'PILZ', clue: 'Weder Pflanze noch Tier', category: 'Natur' },
  { word: 'BAMBUS', clue: 'Schnell wachsendes Riesengras aus Asien', category: 'Natur' },
  { word: 'EFEU', clue: 'Immergrüne Kletterpflanze', category: 'Natur' },

  // ==================== GESCHICHTE (40) ====================
  { word: 'KAISER', clue: 'Höchster Herrscher eines Reiches', category: 'Geschichte' },
  { word: 'PHARAO', clue: 'Herrscher im alten Ägypten', category: 'Geschichte' },
  { word: 'RITTER', clue: 'Gepanzerter Krieger des Mittelalters', category: 'Geschichte' },
  { word: 'WIKINGER', clue: 'Nordische Seefahrer und Krieger', category: 'Geschichte' },
  { word: 'LEGION', clue: 'Heereseinheit der Römer', category: 'Geschichte' },
  { word: 'KOLONIE', clue: 'Von einer Fremdsiedlung beherrschtes Gebiet', category: 'Geschichte' },
  { word: 'PAPYRUS', clue: 'Schreibmaterial der alten Ägypter', category: 'Geschichte' },
  { word: 'AMPHORE', clue: 'Antikes Tongefäß mit zwei Henkeln', category: 'Geschichte' },
  { word: 'GLADIATOR', clue: 'Berufskämpfer im alten Rom', category: 'Geschichte' },
  { word: 'SENAT', clue: 'Rat der Ältesten im alten Rom', category: 'Geschichte' },
  { word: 'AGORA', clue: 'Marktplatz im antiken Griechenland', category: 'Geschichte' },
  { word: 'KATAPULT', clue: 'Antike Belagerungswaffe zum Schleudern', category: 'Geschichte' },
  { word: 'BURG', clue: 'Befestigter Adelssitz im Mittelalter', category: 'Geschichte' },
  { word: 'TURNIER', clue: 'Ritterwettkampf im Mittelalter', category: 'Geschichte' },
  { word: 'VASALL', clue: 'Lehensmann eines Herrschers', category: 'Geschichte' },
  { word: 'FEUDAL', clue: 'Zum Lehenswesen gehörend', category: 'Geschichte' },
  { word: 'ZENSOR', clue: 'Beamter der im alten Rom die Bürger zählte', category: 'Geschichte' },
  { word: 'TRIBUN', clue: 'Volksvertreter im alten Rom', category: 'Geschichte' },
  { word: 'SULTAN', clue: 'Islamischer Herrscher', category: 'Geschichte' },
  { word: 'KALIF', clue: 'Nachfolger Mohammeds als Herrscher', category: 'Geschichte' },
  { word: 'SAMURAI', clue: 'Japanischer Kriegeradel', category: 'Geschichte' },
  { word: 'SHOGUN', clue: 'Militärischer Herrscher in Japan', category: 'Geschichte' },
  { word: 'MONGOLE', clue: 'Reitervolk unter Dschingis Khan', category: 'Geschichte' },
  { word: 'ZARIN', clue: 'Herrscherin im alten Russland', category: 'Geschichte' },
  { word: 'DRUIDE', clue: 'Keltischer Priester und Weiser', category: 'Geschichte' },
  { word: 'GALERIE', clue: 'Langer Gang in Festungen', category: 'Geschichte' },
  { word: 'FESTUNG', clue: 'Stark befestigte Anlage', category: 'Geschichte' },
  { word: 'REFORM', clue: 'Grundlegende Erneuerung oder Umgestaltung', category: 'Geschichte' },
  { word: 'REVOLUTION', clue: 'Gewaltsamer politischer Umsturz', category: 'Geschichte' },
  { word: 'MONARCHIE', clue: 'Staatsform mit König als Oberhaupt', category: 'Geschichte' },
  { word: 'DEMOKRATIE', clue: 'Herrschaft des Volkes', category: 'Geschichte' },
  { word: 'REPUBLIK', clue: 'Staatsform ohne Monarchen', category: 'Geschichte' },
  { word: 'DYNASTIE', clue: 'Herrschergeschlecht über Generationen', category: 'Geschichte' },
  { word: 'KREUZZUG', clue: 'Mittelalterlicher Kriegszug ins Heilige Land', category: 'Geschichte' },
  { word: 'HANDEL', clue: 'Austausch von Waren', category: 'Geschichte' },
  { word: 'PEST', clue: 'Tödliche Seuche des Mittelalters', category: 'Geschichte' },
  { word: 'ABLASS', clue: 'Sündenvergebung gegen Geld (Luther-Zeit)', category: 'Geschichte' },
  { word: 'GUTENBERG', clue: 'Erfinder des Buchdrucks', category: 'Geschichte' },
  { word: 'RENAISSANCE', clue: 'Wiedergeburt der Antike als Epoche', category: 'Geschichte' },
  { word: 'AUFKLAERUNG', clue: 'Geistige Bewegung des 18. Jahrhunderts', category: 'Geschichte' },

  // ==================== MUSIK (35) ====================
  { word: 'GITARRE', clue: 'Sechssaitiges Zupfinstrument', category: 'Musik' },
  { word: 'GEIGE', clue: 'Streichinstrument in Orchestern', category: 'Musik' },
  { word: 'TUBA', clue: 'Tiefstes Blechblasinstrument', category: 'Musik' },
  { word: 'OBOE', clue: 'Holzblasinstrument mit Doppelrohrblatt', category: 'Musik' },
  { word: 'HARFE', clue: 'Großes Saiteninstrument', category: 'Musik' },
  { word: 'ORGEL', clue: 'Großes Tasteninstrument in Kirchen', category: 'Musik' },
  { word: 'PAUKE', clue: 'Große Kesseltrommel im Orchester', category: 'Musik' },
  { word: 'FLOETE', clue: 'Holzblasinstrument quer geblasen', category: 'Musik' },
  { word: 'FAGOTT', clue: 'Tiefes Holzblasinstrument', category: 'Musik' },
  { word: 'CELLO', clue: 'Großes Streichinstrument', category: 'Musik' },
  { word: 'KONTRABASS', clue: 'Größtes Streichinstrument im Orchester', category: 'Musik' },
  { word: 'AKKORD', clue: 'Mehrere Töne gleichzeitig gespielt', category: 'Musik' },
  { word: 'TONLEITER', clue: 'Aufsteigende Folge von Tönen', category: 'Musik' },
  { word: 'TAKT', clue: 'Rhythmische Grundeinheit in der Musik', category: 'Musik' },
  { word: 'TEMPO', clue: 'Geschwindigkeit eines Musikstücks', category: 'Musik' },
  { word: 'REFRAIN', clue: 'Wiederkehrender Teil eines Liedes', category: 'Musik' },
  { word: 'STROPHE', clue: 'Abschnitt eines Liedes oder Gedichts', category: 'Musik' },
  { word: 'MELODIE', clue: 'Folge von Tönen die ein Lied bilden', category: 'Musik' },
  { word: 'RHYTHMUS', clue: 'Zeitliches Muster in der Musik', category: 'Musik' },
  { word: 'CHOR', clue: 'Gruppe von Sängern', category: 'Musik' },
  { word: 'DIRIGENT', clue: 'Leiter eines Orchesters', category: 'Musik' },
  { word: 'VIBRATO', clue: 'Leichtes Schwanken der Tonhöhe', category: 'Musik' },
  { word: 'OKTAVE', clue: 'Intervall von acht Tonstufen', category: 'Musik' },
  { word: 'SAXOPHON', clue: 'Blechernes Holzblasinstrument im Jazz', category: 'Musik' },
  { word: 'TROMPETE', clue: 'Hohes Blechblasinstrument', category: 'Musik' },
  { word: 'POSAUNE', clue: 'Blechblasinstrument mit Zug', category: 'Musik' },
  { word: 'XYLOPHON', clue: 'Stabspiel aus Holz', category: 'Musik' },
  { word: 'BECKEN', clue: 'Runde Metallscheibe als Schlaginstrument', category: 'Musik' },
  { word: 'BANJO', clue: 'Zupfinstrument mit rundem Körper', category: 'Musik' },
  { word: 'UKULELE', clue: 'Kleine hawaiianische Gitarre', category: 'Musik' },
  { word: 'MUNDHARMONIKA', clue: 'Kleines Blasinstrument in der Hand', category: 'Musik' },
  { word: 'DUDELSACK', clue: 'Schottisches Blasinstrument mit Sack', category: 'Musik' },
  { word: 'MANDOLINE', clue: 'Kleines Zupfinstrument mit Doppelsaiten', category: 'Musik' },
  { word: 'KLARINETTE', clue: 'Holzblasinstrument mit einfachem Rohrblatt', category: 'Musik' },
  { word: 'TRIANGEL', clue: 'Dreieckiges Schlaginstrument aus Metall', category: 'Musik' },

  // ==================== ALLGEMEINWISSEN (60) ====================
  { word: 'ANKER', clue: 'Hält das Schiff am Platz', category: 'Allgemein' },
  { word: 'KOMPASS', clue: 'Zeigt immer nach Norden', category: 'Allgemein' },
  { word: 'PENDEL', clue: 'Schwingendes Gewicht an einer Schnur', category: 'Allgemein' },
  { word: 'GLOBUS', clue: 'Kugelförmiges Modell der Erde', category: 'Allgemein' },
  { word: 'MOSAIK', clue: 'Zusammengesetztes Steinbild', category: 'Allgemein' },
  { word: 'ADVENT', clue: 'Vorweihnachtliche Zeit', category: 'Allgemein' },
  { word: 'ZUFALL', clue: 'Unvorhersehbares Ereignis', category: 'Allgemein' },
  { word: 'LOGIK', clue: 'Lehre vom richtigen Denken', category: 'Allgemein' },
  { word: 'UTOPIE', clue: 'Vorstellung einer idealen Gesellschaft', category: 'Allgemein' },
  { word: 'IRONIE', clue: 'Das Gegenteil meinen von dem was man sagt', category: 'Allgemein' },
  { word: 'TABAK', clue: 'Pflanze in Zigaretten', category: 'Allgemein' },
  { word: 'AMULETT', clue: 'Schützender Glücksbringer zum Tragen', category: 'Allgemein' },
  { word: 'SPHINX', clue: 'Ägyptisches Fabelwesen mit Löwenkörper', category: 'Allgemein' },
  { word: 'ORAKEL', clue: 'Antike Prophezeiungsstätte', category: 'Allgemein' },
  { word: 'RUINE', clue: 'Verfallenes Bauwerk', category: 'Allgemein' },
  { word: 'VERLAG', clue: 'Unternehmen das Bücher herausgibt', category: 'Allgemein' },
  { word: 'PATENT', clue: 'Schutzrecht für eine Erfindung', category: 'Allgemein' },
  { word: 'RITUAL', clue: 'Feierliche Handlung nach fester Ordnung', category: 'Allgemein' },
  { word: 'MOTTO', clue: 'Leitspruch oder Wahlspruch', category: 'Allgemein' },
  { word: 'ZITAT', clue: 'Wörtlich wiedergegebener Ausspruch', category: 'Allgemein' },
  { word: 'ALIBI', clue: 'Nachweis der Abwesenheit vom Tatort', category: 'Allgemein' },
  { word: 'BONUS', clue: 'Zusätzliche Belohnung oder Vergütung', category: 'Allgemein' },
  { word: 'CHAOS', clue: 'Völlige Unordnung', category: 'Allgemein' },
  { word: 'DEBUT', clue: 'Erster öffentlicher Auftritt', category: 'Allgemein' },
  { word: 'ENIGMA', clue: 'Berühmte Verschlüsselungsmaschine', category: 'Allgemein' },
  { word: 'FAUNA', clue: 'Gesamtheit der Tierwelt', category: 'Allgemein' },
  { word: 'FLORA', clue: 'Gesamtheit der Pflanzenwelt', category: 'Allgemein' },
  { word: 'KAPITEL', clue: 'Abschnitt eines Buches', category: 'Allgemein' },
  { word: 'HORIZONT', clue: 'Linie wo Himmel und Erde sich treffen', category: 'Allgemein' },
  { word: 'INSTINKT', clue: 'Angeborenes Verhaltensmuster', category: 'Allgemein' },
  { word: 'LATERNE', clue: 'Lichtquelle an der Straße', category: 'Allgemein' },
  { word: 'MINIATUR', clue: 'Stark verkleinertes Abbild', category: 'Allgemein' },
  { word: 'NIMBUS', clue: 'Besonderer Ruf oder Glorienschein', category: 'Allgemein' },
  { word: 'OLYMP', clue: 'Berg der griechischen Götter', category: 'Allgemein' },
  { word: 'PALAST', clue: 'Prachtvolles Wohngebäude eines Herrschers', category: 'Allgemein' },
  { word: 'RANKE', clue: 'Greifendes Pflanzenorgan zum Klettern', category: 'Allgemein' },
  { word: 'SIEGEL', clue: 'Geprägte Verschlussmarke', category: 'Allgemein' },
  { word: 'TALISMAN', clue: 'Gegenstand der Glück bringen soll', category: 'Allgemein' },
  { word: 'VAMPIR', clue: 'Blutsaugender Untoter der Sage', category: 'Allgemein' },
  { word: 'WAPPEN', clue: 'Hoheitszeichen einer Familie oder Stadt', category: 'Allgemein' },
  { word: 'CHRONIK', clue: 'Geschichtliche Aufzeichnung', category: 'Allgemein' },
  { word: 'DOZENT', clue: 'Lehrkraft an einer Hochschule', category: 'Allgemein' },
  { word: 'EXAMEN', clue: 'Abschlussprüfung an der Universität', category: 'Allgemein' },
  { word: 'GALGEN', clue: 'Hinrichtungsgestell zum Hängen', category: 'Allgemein' },
  { word: 'KANZEL', clue: 'Erhöhter Predigtplatz in der Kirche', category: 'Allgemein' },
  { word: 'KURIER', clue: 'Eilbote der Nachrichten überbringt', category: 'Allgemein' },
  { word: 'KOMIKER', clue: 'Person die andere zum Lachen bringt', category: 'Allgemein' },
  { word: 'LITERAT', clue: 'Schriftsteller oder Buchgelehrter', category: 'Allgemein' },
  { word: 'NOVIZE', clue: 'Neuling in einem Kloster', category: 'Allgemein' },
  { word: 'PIRAT', clue: 'Seeräuber auf hoher See', category: 'Allgemein' },
  { word: 'RABBI', clue: 'Jüdischer Gelehrter und Lehrer', category: 'Allgemein' },
  { word: 'SUENDE', clue: 'Religiöser Verstoß gegen Gottes Gebote', category: 'Allgemein' },
  { word: 'TUTOR', clue: 'Privatlehrer oder Betreuer', category: 'Allgemein' },
  { word: 'VISUM', clue: 'Einreisegenehmigung in ein Land', category: 'Allgemein' },
  { word: 'ZENITH', clue: 'Höchster Punkt am Himmel über einem', category: 'Allgemein' },
  { word: 'PUZZLE', clue: 'Zusammensetzspiel aus Teilen', category: 'Allgemein' },
  { word: 'DOMINO', clue: 'Spiel mit rechteckigen Steinen', category: 'Allgemein' },
  { word: 'SCHACH', clue: 'Brettspiel der Könige', category: 'Allgemein' },
  { word: 'DAME', clue: 'Brettspiel mit diagonalen Zügen', category: 'Allgemein' },
  { word: 'JOKER', clue: 'Trumpfkarte die alles sein kann', category: 'Allgemein' },

  // ==================== MEDIZIN (30) ====================
  { word: 'SKALPELL', clue: 'Chirurgisches Schneideinstrument', category: 'Medizin' },
  { word: 'DIAGNOSE', clue: 'Feststellung einer Krankheit', category: 'Medizin' },
  { word: 'THERAPIE', clue: 'Behandlung einer Krankheit', category: 'Medizin' },
  { word: 'IMPFUNG', clue: 'Vorbeugende Schutzmaßnahme gegen Krankheiten', category: 'Medizin' },
  { word: 'VIRUS', clue: 'Krankheitserreger kleiner als Bakterien', category: 'Medizin' },
  { word: 'FIEBER', clue: 'Erhöhte Körpertemperatur', category: 'Medizin' },
  { word: 'PULS', clue: 'Herzschlag fühlbar am Handgelenk', category: 'Medizin' },
  { word: 'ORGAN', clue: 'Funktionseinheit des Körpers wie Herz oder Lunge', category: 'Medizin' },
  { word: 'NIERE', clue: 'Paariges Organ zur Blutreinigung', category: 'Medizin' },
  { word: 'LEBER', clue: 'Größtes inneres Organ des Menschen', category: 'Medizin' },
  { word: 'MILZ', clue: 'Organ des Immunsystems im linken Oberbauch', category: 'Medizin' },
  { word: 'MUSKEL', clue: 'Gewebe das Bewegung ermöglicht', category: 'Medizin' },
  { word: 'SEHNE', clue: 'Verbindung zwischen Muskel und Knochen', category: 'Medizin' },
  { word: 'GELENK', clue: 'Bewegliche Knochenverbindung', category: 'Medizin' },
  { word: 'INSULIN', clue: 'Hormon das den Blutzucker senkt', category: 'Medizin' },
  { word: 'ANTIBIOTIKUM', clue: 'Medikament gegen Bakterien', category: 'Medizin' },
  { word: 'ALLERGIE', clue: 'Überreaktion des Immunsystems', category: 'Medizin' },
  { word: 'SYMPTOM', clue: 'Anzeichen einer Krankheit', category: 'Medizin' },
  { word: 'SYNAPSE', clue: 'Kontaktstelle zwischen Nervenzellen', category: 'Medizin' },
  { word: 'ARTERIE', clue: 'Blutgefäß vom Herzen weg', category: 'Medizin' },
  { word: 'VENE', clue: 'Blutgefäß zum Herzen hin', category: 'Medizin' },
  { word: 'RETINA', clue: 'Netzhaut des Auges', category: 'Medizin' },
  { word: 'PUPILLE', clue: 'Schwarzer Kreis im Auge', category: 'Medizin' },
  { word: 'MANDEL', clue: 'Lymphgewebe im Rachen', category: 'Medizin' },
  { word: 'PROTHESE', clue: 'Künstlicher Körperersatz', category: 'Medizin' },
  { word: 'KATHETER', clue: 'Medizinischer Schlauch für Körperhohlräume', category: 'Medizin' },
  { word: 'BANDAGE', clue: 'Elastischer Verband zur Stützung', category: 'Medizin' },
  { word: 'DEFIBRILLATOR', clue: 'Gerät zur Herzwiederbelebung mit Strom', category: 'Medizin' },
  { word: 'STETHOSKOP', clue: 'Abhörgerät für Herz und Lunge', category: 'Medizin' },
  { word: 'REZEPT', clue: 'Ärztliche Verordnung für Medikamente', category: 'Medizin' },

  // ==================== MATHEMATIK (20) ====================
  { word: 'INTEGRAL', clue: 'Berechnung der Fläche unter einer Kurve', category: 'Mathematik' },
  { word: 'VEKTOR', clue: 'Größe mit Betrag und Richtung', category: 'Mathematik' },
  { word: 'MATRIX', clue: 'Rechteckige Anordnung von Zahlen', category: 'Mathematik' },
  { word: 'RADIUS', clue: 'Halber Durchmesser eines Kreises', category: 'Mathematik' },
  { word: 'TANGENTE', clue: 'Gerade die einen Kreis berührt', category: 'Mathematik' },
  { word: 'MEDIAN', clue: 'Mittlerer Wert einer Zahlenreihe', category: 'Mathematik' },
  { word: 'BRUCH', clue: 'Zahl als Zähler geteilt durch Nenner', category: 'Mathematik' },
  { word: 'SUMME', clue: 'Ergebnis einer Addition', category: 'Mathematik' },
  { word: 'FAKTOR', clue: 'Zahl die multipliziert wird', category: 'Mathematik' },
  { word: 'QUOTIENT', clue: 'Ergebnis einer Division', category: 'Mathematik' },
  { word: 'POTENZ', clue: 'Zahl hoch eine andere Zahl', category: 'Mathematik' },
  { word: 'WURZEL', clue: 'Umkehroperation des Potenzierens', category: 'Mathematik' },
  { word: 'PRISMA', clue: 'Geometrischer Körper mit parallelen Grundflächen', category: 'Mathematik' },
  { word: 'PYRAMIDE', clue: 'Geometrischer Körper mit Spitze', category: 'Mathematik' },
  { word: 'ZYLINDER', clue: 'Geometrischer Körper wie eine Dose', category: 'Mathematik' },
  { word: 'KEGEL', clue: 'Geometrischer Körper mit runder Grundfläche und Spitze', category: 'Mathematik' },
  { word: 'TRAPEZ', clue: 'Viereck mit einem Paar paralleler Seiten', category: 'Mathematik' },
  { word: 'PARABEL', clue: 'U-förmige mathematische Kurve', category: 'Mathematik' },
  { word: 'SINUS', clue: 'Trigonometrische Funktion', category: 'Mathematik' },
  { word: 'COSINUS', clue: 'Trigonometrische Funktion neben Sinus', category: 'Mathematik' },
];

export const solutionWords = [
  'KLUG', 'WORT', 'QUIZ', 'GENIE', 'SPASS',
  'PROFI', 'SUPER', 'HELD', 'TOLL', 'KLAR',
  'STARK', 'FEIN', 'COOL', 'PRIMA', 'BRAVO',
  'PFEIL', 'STERN', 'BLITZ', 'KRAFT', 'GEIST',
  'ADLER', 'TIGER', 'LOTUS', 'FUCHS', 'STOLZ',
];
